/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.bc.CounterPartySettleInfo', null, global);
goog.exportSymbol('proto.bc.CrossTxSettlementToWatch', null, global);
goog.exportSymbol('proto.bc.DbValue', null, global);
goog.exportSymbol('proto.bc.Schedules', null, global);
goog.exportSymbol('proto.bc.SettleSchedule', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.DbValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.DbValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bc.DbValue.displayName = 'proto.bc.DbValue';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.DbValue.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.DbValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.DbValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.DbValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: msg.getData_asB64(),
    version: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isNative: jspb.Message.getFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.DbValue}
 */
proto.bc.DbValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.DbValue;
  return proto.bc.DbValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.DbValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.DbValue}
 */
proto.bc.DbValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsNative(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.DbValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.DbValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.DbValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.DbValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getIsNative();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.bc.DbValue.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.DbValue.prototype.setType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes data = 2;
 * @return {!(string|Uint8Array)}
 */
proto.bc.DbValue.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.bc.DbValue.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.bc.DbValue.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value */
proto.bc.DbValue.prototype.setData = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional int32 version = 3;
 * @return {number}
 */
proto.bc.DbValue.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.bc.DbValue.prototype.setVersion = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool is_native = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.bc.DbValue.prototype.getIsNative = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.bc.DbValue.prototype.setIsNative = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.CounterPartySettleInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.CounterPartySettleInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bc.CounterPartySettleInfo.displayName = 'proto.bc.CounterPartySettleInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.CounterPartySettleInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.CounterPartySettleInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.CounterPartySettleInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.CounterPartySettleInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    settled: jspb.Message.getFieldWithDefault(msg, 1, false),
    txHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    outputIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sendsAddress: jspb.Message.getFieldWithDefault(msg, 4, ""),
    scheduled: jspb.Message.getFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.CounterPartySettleInfo}
 */
proto.bc.CounterPartySettleInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.CounterPartySettleInfo;
  return proto.bc.CounterPartySettleInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.CounterPartySettleInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.CounterPartySettleInfo}
 */
proto.bc.CounterPartySettleInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSettled(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxHash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOutputIndex(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendsAddress(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setScheduled(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.CounterPartySettleInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.CounterPartySettleInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.CounterPartySettleInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.CounterPartySettleInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSettled();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getTxHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOutputIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSendsAddress();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getScheduled();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool settled = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.bc.CounterPartySettleInfo.prototype.getSettled = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.bc.CounterPartySettleInfo.prototype.setSettled = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string tx_hash = 2;
 * @return {string}
 */
proto.bc.CounterPartySettleInfo.prototype.getTxHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bc.CounterPartySettleInfo.prototype.setTxHash = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 output_index = 3;
 * @return {number}
 */
proto.bc.CounterPartySettleInfo.prototype.getOutputIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.bc.CounterPartySettleInfo.prototype.setOutputIndex = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string sends_address = 4;
 * @return {string}
 */
proto.bc.CounterPartySettleInfo.prototype.getSendsAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.bc.CounterPartySettleInfo.prototype.setSendsAddress = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool scheduled = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.bc.CounterPartySettleInfo.prototype.getScheduled = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.bc.CounterPartySettleInfo.prototype.setScheduled = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.CrossTxSettlementToWatch = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.CrossTxSettlementToWatch.repeatedFields_, null);
};
goog.inherits(proto.bc.CrossTxSettlementToWatch, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bc.CrossTxSettlementToWatch.displayName = 'proto.bc.CrossTxSettlementToWatch';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.CrossTxSettlementToWatch.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.CrossTxSettlementToWatch.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.CrossTxSettlementToWatch.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.CrossTxSettlementToWatch} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.CrossTxSettlementToWatch.toObject = function(includeInstance, msg) {
  var f, obj = {
    settleEndsAt: jspb.Message.getFieldWithDefault(msg, 1, 0),
    takerSettleInfoList: jspb.Message.toObjectList(msg.getTakerSettleInfoList(),
    proto.bc.CounterPartySettleInfo.toObject, includeInstance),
    makerSettleInfoList: jspb.Message.toObjectList(msg.getMakerSettleInfoList(),
    proto.bc.CounterPartySettleInfo.toObject, includeInstance),
    shift: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.CrossTxSettlementToWatch}
 */
proto.bc.CrossTxSettlementToWatch.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.CrossTxSettlementToWatch;
  return proto.bc.CrossTxSettlementToWatch.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.CrossTxSettlementToWatch} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.CrossTxSettlementToWatch}
 */
proto.bc.CrossTxSettlementToWatch.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSettleEndsAt(value);
      break;
    case 2:
      var value = new proto.bc.CounterPartySettleInfo;
      reader.readMessage(value,proto.bc.CounterPartySettleInfo.deserializeBinaryFromReader);
      msg.addTakerSettleInfo(value);
      break;
    case 3:
      var value = new proto.bc.CounterPartySettleInfo;
      reader.readMessage(value,proto.bc.CounterPartySettleInfo.deserializeBinaryFromReader);
      msg.addMakerSettleInfo(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setShift(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.CrossTxSettlementToWatch.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.CrossTxSettlementToWatch.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.CrossTxSettlementToWatch} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.CrossTxSettlementToWatch.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSettleEndsAt();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTakerSettleInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.bc.CounterPartySettleInfo.serializeBinaryToWriter
    );
  }
  f = message.getMakerSettleInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.bc.CounterPartySettleInfo.serializeBinaryToWriter
    );
  }
  f = message.getShift();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 settle_ends_at = 1;
 * @return {number}
 */
proto.bc.CrossTxSettlementToWatch.prototype.getSettleEndsAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.bc.CrossTxSettlementToWatch.prototype.setSettleEndsAt = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated CounterPartySettleInfo taker_settle_info = 2;
 * @return {!Array<!proto.bc.CounterPartySettleInfo>}
 */
proto.bc.CrossTxSettlementToWatch.prototype.getTakerSettleInfoList = function() {
  return /** @type{!Array<!proto.bc.CounterPartySettleInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.CounterPartySettleInfo, 2));
};


/** @param {!Array<!proto.bc.CounterPartySettleInfo>} value */
proto.bc.CrossTxSettlementToWatch.prototype.setTakerSettleInfoList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bc.CounterPartySettleInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.CounterPartySettleInfo}
 */
proto.bc.CrossTxSettlementToWatch.prototype.addTakerSettleInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bc.CounterPartySettleInfo, opt_index);
};


proto.bc.CrossTxSettlementToWatch.prototype.clearTakerSettleInfoList = function() {
  this.setTakerSettleInfoList([]);
};


/**
 * repeated CounterPartySettleInfo maker_settle_info = 3;
 * @return {!Array<!proto.bc.CounterPartySettleInfo>}
 */
proto.bc.CrossTxSettlementToWatch.prototype.getMakerSettleInfoList = function() {
  return /** @type{!Array<!proto.bc.CounterPartySettleInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.CounterPartySettleInfo, 3));
};


/** @param {!Array<!proto.bc.CounterPartySettleInfo>} value */
proto.bc.CrossTxSettlementToWatch.prototype.setMakerSettleInfoList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.bc.CounterPartySettleInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.CounterPartySettleInfo}
 */
proto.bc.CrossTxSettlementToWatch.prototype.addMakerSettleInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.bc.CounterPartySettleInfo, opt_index);
};


proto.bc.CrossTxSettlementToWatch.prototype.clearMakerSettleInfoList = function() {
  this.setMakerSettleInfoList([]);
};


/**
 * optional int64 shift = 4;
 * @return {number}
 */
proto.bc.CrossTxSettlementToWatch.prototype.getShift = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bc.CrossTxSettlementToWatch.prototype.setShift = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.SettleSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.SettleSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bc.SettleSchedule.displayName = 'proto.bc.SettleSchedule';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.SettleSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.SettleSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.SettleSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.SettleSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    addrFrom: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addrTo: jspb.Message.getFieldWithDefault(msg, 2, ""),
    bridgedChain: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bcHeight: jspb.Message.getFieldWithDefault(msg, 4, 0),
    bridgedChainHash: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.SettleSchedule}
 */
proto.bc.SettleSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.SettleSchedule;
  return proto.bc.SettleSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.SettleSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.SettleSchedule}
 */
proto.bc.SettleSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddrFrom(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddrTo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBridgedChain(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBcHeight(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBridgedChainHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.SettleSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.SettleSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.SettleSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.SettleSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddrFrom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddrTo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBridgedChain();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBcHeight();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getBridgedChainHash();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string addr_from = 1;
 * @return {string}
 */
proto.bc.SettleSchedule.prototype.getAddrFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.SettleSchedule.prototype.setAddrFrom = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string addr_to = 2;
 * @return {string}
 */
proto.bc.SettleSchedule.prototype.getAddrTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bc.SettleSchedule.prototype.setAddrTo = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string bridged_chain = 3;
 * @return {string}
 */
proto.bc.SettleSchedule.prototype.getBridgedChain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.bc.SettleSchedule.prototype.setBridgedChain = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 bc_height = 4;
 * @return {number}
 */
proto.bc.SettleSchedule.prototype.getBcHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bc.SettleSchedule.prototype.setBcHeight = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string bridged_chain_hash = 5;
 * @return {string}
 */
proto.bc.SettleSchedule.prototype.getBridgedChainHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.bc.SettleSchedule.prototype.setBridgedChainHash = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.Schedules = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.Schedules.repeatedFields_, null);
};
goog.inherits(proto.bc.Schedules, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bc.Schedules.displayName = 'proto.bc.Schedules';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.Schedules.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.Schedules.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.Schedules.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.Schedules} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Schedules.toObject = function(includeInstance, msg) {
  var f, obj = {
    schedulesList: jspb.Message.toObjectList(msg.getSchedulesList(),
    proto.bc.SettleSchedule.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.Schedules}
 */
proto.bc.Schedules.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.Schedules;
  return proto.bc.Schedules.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.Schedules} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.Schedules}
 */
proto.bc.Schedules.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bc.SettleSchedule;
      reader.readMessage(value,proto.bc.SettleSchedule.deserializeBinaryFromReader);
      msg.addSchedules(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.Schedules.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.Schedules.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.Schedules} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Schedules.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchedulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bc.SettleSchedule.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SettleSchedule schedules = 1;
 * @return {!Array<!proto.bc.SettleSchedule>}
 */
proto.bc.Schedules.prototype.getSchedulesList = function() {
  return /** @type{!Array<!proto.bc.SettleSchedule>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.SettleSchedule, 1));
};


/** @param {!Array<!proto.bc.SettleSchedule>} value */
proto.bc.Schedules.prototype.setSchedulesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.SettleSchedule=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.SettleSchedule}
 */
proto.bc.Schedules.prototype.addSchedules = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.SettleSchedule, opt_index);
};


proto.bc.Schedules.prototype.clearSchedulesList = function() {
  this.setSchedulesList([]);
};


goog.object.extend(exports, proto.bc);
