/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.bcsdksdk.MessageGetObjectsRequest', null, global);
goog.exportSymbol('proto.bcsdksdk.MsgType', null, global);
goog.exportSymbol('proto.bcsdksdk.ObjType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bcsdksdk.MessageGetObjectsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bcsdksdk.MessageGetObjectsRequest, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bcsdksdk.MessageGetObjectsRequest.displayName = 'proto.bcsdksdk.MessageGetObjectsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bcsdksdk.MessageGetObjectsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bcsdksdk.MessageGetObjectsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bcsdksdk.MessageGetObjectsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    body: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bcsdksdk.MessageGetObjectsRequest}
 */
proto.bcsdksdk.MessageGetObjectsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bcsdksdk.MessageGetObjectsRequest;
  return proto.bcsdksdk.MessageGetObjectsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bcsdksdk.MessageGetObjectsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bcsdksdk.MessageGetObjectsRequest}
 */
proto.bcsdksdk.MessageGetObjectsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.bcsdksdk.MsgType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!proto.bcsdksdk.ObjType} */ (reader.readEnum());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bcsdksdk.MessageGetObjectsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bcsdksdk.MessageGetObjectsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bcsdksdk.MessageGetObjectsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBody();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional MsgType type = 1;
 * @return {!proto.bcsdksdk.MsgType}
 */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.getType = function() {
  return /** @type {!proto.bcsdksdk.MsgType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.bcsdksdk.MsgType} value */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ObjType body = 2;
 * @return {!proto.bcsdksdk.ObjType}
 */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.getBody = function() {
  return /** @type {!proto.bcsdksdk.ObjType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.bcsdksdk.ObjType} value */
proto.bcsdksdk.MessageGetObjectsRequest.prototype.setBody = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.bcsdksdk.ObjType = {
  BLOCKHEADERS: 0,
  BLOCKBODIES: 1,
  BLOCKTRANSACTIONS: 2,
  ROVERBESTHEIGHTS: 3,
  ROVERBLOCKHEADERS: 4,
  ROVERBLOCKBODIES: 5,
  ROVERTRANSACTIONHEADERS: 6,
  ROVERMARKEDHEADERS: 7
};

/**
 * @enum {number}
 */
proto.bcsdksdk.MsgType = {
  GETOBJECTSREQUEST: 0
};

goog.object.extend(exports, proto.bcsdksdk);
