name: CI
on: push

jobs:
  test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # was master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install -g yarn
      - name: Install JS dependencies
        run: yarn
      - name: Run tslint
        run: yarn run tslint --project .
      - name: Notify TG if tslint failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} tslint failed on "${{ github.event.head_commit.message }}" - ${{ github.actor}} please fix your commit'
      - name: Run tests
        run: yarn run test
      - name: Notify TG if build failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} test failed on "${{ github.event.head_commit.message }}" - ${{ github.actor}} please fix your commit'
      - name: Try to compile
        run: yarn run compile
      - name: Notify TG if compile failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} compilation failed on "${{ github.event.head_commit.message }}" - ${{ github.actor}} please fix your commit'
