name: CI
on: push

jobs:
  tslint:
    runs-on: ubuntu-latest
    name: tslint
    steps:
      - uses: actions/checkout@v1 # was master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install
      - name: Run tslint
        run: yarn run tslint --project .
      - name: Notify TG if tslint failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} tslint failed on "${{ github.event.head_commit.message }}" (build log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) - ${{ github.actor}} please fix your commit'


  unit-tests:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@v1 # was master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install
      - name: Run tests
        run: yarn run test
      - name: Notify TG if build failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} unit tests did not pass on "${{ github.event.head_commit.message }}" (build log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) - ${{ github.actor}} please fix your commit'


  compile:
    runs-on: ubuntu-latest
    name: typescript compile
    steps:
      - uses: actions/checkout@v1 # was master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install
      - name: Try to compile
        run: yarn run compile
      - name: Notify TG if compile failed
        if: failure()
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.BC_CORE_CHAT_ID }}
          token: ${{ secrets.BC_DEV_BOT_TOKEN }}
          message: '❌ ${{ github.repository }} compilation failed on "${{ github.event.head_commit.message }}" (build log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) - ${{ github.actor}} please fix your commit'
